### Получение всех пользователей
GET http://localhost:8080/users.getAll?limit=50&offset=0

### Получение всех обьявлений
GET http://localhost:8080/ads.getAll?limit=50&offset=0

### Получение всех категорий
GET http://localhost:8080/categories.getAll?limit=50&offset=0

### Получение всех сообщений
GET http://localhost:8080/message.getAll?limit=50&offset=0